### Get a list of all registered companies
GET http://localhost:3000/company

### Get a single company by ID
GET http://localhost:3000/company/601b75ed5decff03f2aa52af

### Update a company using ID
PATCH http://localhost:3000/company/601b75ed5decff03f2aa52af
Content-Type: application/json

{
  "name": "Solute GH limited"
}

### Register a new company
POST http://localhost:3000/company/register
Content-Type: application/json

{
  "name": "Node JS is lit",
  "email": "trye@gmail.com",
  "password":"pass123y",
  "phone": "0554345678"
}

### Delete a single company using ID
DELETE http://localhost:3000/company/601be7f18e17b1230218261c

### Get a list of all registered users
GET http://localhost:3000/users

### Get a single user by ID
GET http://localhost:3000/users/601bfbef81adda3812712f30

### Update a user using ID
PATCH http://localhost:3000/users/601bfbef81adda3812712f30
Content-Type: application/json

{
 
}

### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "Ernest Gaisie",
  "email": "ernest@gmail.com",
  "password": "password",
  "phone": "05534324",
  "experience": 2
}

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "ernest@gmail.com",
  "password": "password"
}

### Hit unknown endpoint
GET http://localhost:3000/unknown

