### Get a list of all registered companies
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTI3MTI2MjksImV4cCI6MTYxMjcxMjY0OSwiYXVkIjoiNjAxZDViOWM1Yzk4N2IwNmM3OWYyNWE3IiwiaXNzIjoic29sdXRlLmNvbSJ9.dPpPlYgckZdnujhC0S6VB42hS07-anHuJtSzu_t8zVY

### GET new access and refresh tokens
POST  http://localhost:3000/auth/refreshToken
Content-Type: application/json

{
  "refreshToken": ""
}

###Get a list of all registered companies 
GET http://localhost:3000/company?page=1&size=15


### Get a single company by ID
GET http://localhost:3000/company/601d5b9c5c987b06c79f25a7

### Update a company using ID
PATCH http://localhost:3000/company/601b75ed5decff03f2aa52af
Content-Type: application/json

{
  "name": "Solute GH limited"
}

### Register a new company
POST http://localhost:3000/company/register
Content-Type: application/json

{
  "name": "appgharage limited",
  "email": "apgharage@gmail.com",
  "password":"pleaseworkout",
  "phone": "0244532222"
}

### Login as a company
POST http://localhost:3000/company/login
Content-Type: application/json

{
  "email": "",
  "password":""
}

### Delete a single company using ID
DELETE http://localhost:3000/company/602cb994a10536119aee1663

### Get a list of all registered users
GET http://localhost:3000/users?page=1&size=20

### Get a single user by ID
GET http://localhost:3000/users/601bfbef81adda3812712f30

### Update a user using ID
PATCH http://localhost:3000/users/601bfbef81adda3812712f30
Content-Type: application/json

{
 
}

### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "reverended",
  "email": "reverended@gmail.com",
  "password": "allthatneedstobedone",
  "phone": "0244520953",
  "experience": 2
}

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "hkanner21@gmail.com",
  "password": "allthatneedstobedone"
}

###Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": ""
}

### Hit unknown endpoint
GET http://localhost:3000/unknown

